AWSTemplateFormatVersion: 2010-09-09
Description: Creates the mirza postgres DB
Parameters:
  DBPassword:
    Description: RDS password
    Type: String
  DBSecurityGroupId:
    Description: Security group ID for RDS
    Type: String
  DBName:
    Description: Postgres DB name
    Type: String

Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName
      Engine: postgres
      MasterUsername: postgres
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Ref DBName
      PubliclyAccessible: false
      VPCSecurityGroups:
        - !Ref DBSecurityGroupId
      AllocatedStorage: 20
      MasterUserPassword: !Ref DBPassword

Outputs:
  DBHostname:
    Description: Hostname for DB
    Value: !GetAtt DBInstance.Endpoint.Address
    Export:
      Name: !Sub ${AWS::StackName}::DBHostname
  DBName:
    Description: Postgres DB name
    Value: !Ref DBName
    Export:
      Name: !Sub ${AWS::StackName}::DBName

  
